from django.urls import path
from .views import (RegisterView,
                    LogoutView,
                    GetProfileView,
                    UpdateProfileView,
                    WeightStatListCreateView,
                    FriendsListView,
                    FriendRequestCreateView,
                    FriendRequestListView,
                    FriendRequestUpdateView,
                    RemoveFriendView,
                    UserSearchView,
                    BattleListView,
                    BattleDetailView,
                    BattleJoinView,
                    BattleLeaveView,
                    BattleLeaderboardView,
                    BattleInviteView,
                    PendingBattleInvitationsView,
                    AcceptBattleInvitationView,
                    RejectBattleInvitationView,
                    StartBattleView
                )
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path('api/register/', RegisterView.as_view(), name='register'),
    path('api/login/', TokenObtainPairView.as_view(), name='login'),  # JWT login
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/logout/', LogoutView.as_view(), name='logout'),
    path('api/profile/', GetProfileView.as_view(), name='get_profile'),
    path('api/profile/update/', UpdateProfileView.as_view(), name='update_profile'),
    path('api/weight-stats/', WeightStatListCreateView.as_view(), name='weight_stat_list_create'),
    path('api/friends/', FriendsListView.as_view(), name='friends_list'),
    path('api/friends/request/send/', FriendRequestCreateView.as_view(), name='friend_request_send'),
    path('api/friends/requests/', FriendRequestListView.as_view(), name='friend_requests_list'),
    path('api/friends/requests/<int:pk>/<str:action>/', FriendRequestUpdateView.as_view(), name='friend_request_action'),
    path('api/friends/remove/<int:pk>/', RemoveFriendView.as_view(), name='remove_friend'),
    path('api/users/search/', UserSearchView.as_view(), name='user_search'),
    path('api/battles/', BattleListView.as_view(), name='battle_list'),
    path('api/battles/<int:pk>/', BattleDetailView.as_view(), name='battle_detail'),
    path('api/battles/<int:pk>/join/', BattleJoinView.as_view(), name='battle_join'),
    path('api/battles/<int:pk>/leave/', BattleLeaveView.as_view(), name='battle_leave'),
    path('api/battles/<int:pk>/leaderboard/', BattleLeaderboardView.as_view(), name='battle_leaderboard'),
    path('api/battles/<int:pk>/invite/', BattleInviteView.as_view(), name='battle_invite'),
    path('api/battles/invitations/pending/', PendingBattleInvitationsView.as_view(), name='pending_invitations'),
    path('api/battles/invitations/<int:invitation_id>/accept/', AcceptBattleInvitationView.as_view(), name='accept_invitation'),
    path('api/battles/invitations/<int:invitation_id>/reject/', RejectBattleInvitationView.as_view(), name='reject_invitation'),
    path('api/battles/<int:pk>/start/', StartBattleView.as_view(), name='start_battle'),
]