# Generated by Django 5.1.2 on 2024-11-05 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defatify', '0004_friendrequest_friendship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unit_preference',
            field=models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='metric', max_length=10),
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('stat_goal', 'Stat Goal'), ('duration', 'Duration')], max_length=10)),
                ('weight_param', models.CharField(choices=[('weight', 'Weight'), ('body_fat', 'Body Fat'), ('muscle_mass', 'Muscle Mass')], max_length=20)),
                ('goal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_battles', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='battles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BattleStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(max_length=20)),
                ('starting_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='defatify.battle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
