# Generated by Django 5.1.2 on 2024-11-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defatify', '0007_battle_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('deleted', 'Deleted')], default='not_started', max_length=20),
        ),
    ]
