# Generated by Django 5.1.2 on 2024-11-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defatify', '0008_battle_deleted_at_alter_battle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlestatistic',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='battlestatistic',
            name='starting_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
